lib/mock_redis/database.rb
spec/commands/script_spec.rb

Hey,
this is not a complete implementation obviously, but I think a complete one is not even feasible (unless you want to include a Lua interpreter in this gem). :smile: 
I encountered this after updating to `redlock-0.1.4`, they introduced script loading into the locking mechanism and that's when my test suite broke, since `mock_redis` does not yet respond to `#script`.
What do you think the best solution here would be? :)
I'm leaning towards that `mock_redis` should at least pretend to understand everything a regular Redis connection can.
Thank you for your gem!

Add a stub for script command

---

README.md
lib/mock_redis/database.rb
spec/commands/eval_spec.rb
spec/commands/evalsha_spec.rb

@sds here are the missing scripting command stubs. :smile: 
Ref: https://github.com/brigade/mock_redis/pull/112

Implement missing scripting command stubs: eval, evalsha

---

lib/mock_redis/zset_methods.rb
spec/commands/zrange_spec.rb

The Redis zrange command can handle out of bounds negative start index. Ruby arrays can't do this (returns nil. See: http://apidock.com/ruby/Array/%5B%5D). This commit provides a small update to the mock zrange command to provide this functionality. Discovered when writing a test that invoked a method which used this command: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L519

Handle negative out of bounds start in zrange

---

lib/mock_redis/zset_methods.rb
spec/commands/zrange_spec.rb

Addresses https://github.com/brigade/mock_redis/issues/131. 
The existing code was capping the negative STOP argument at the negative size of the zset. But when START is 0, this means that the first element of the zset is included no matter the STOP argument.

Fix #zrange behavior with negative stop argument

---

README.md
lib/mock_redis/string_methods.rb
lib/mock_redis/utility_methods.rb
spec/commands/bitfield_spec.rb

This adds support for the bitfield command and its subcommands. See https://redis.io/commands/bitfield
- All four bitfield subcommands are supported (get, set, incrby, overflow)
- Supports the three documented overflow methods (wrap, sat, fail)
- Uses the existing getbit and setbit commands
- Includes test coverage for all new features

Add support for bitfield command

---

lib/mock_redis/future.rb
lib/mock_redis/pipelined_wrapper.rb
spec/transactions_spec.rb

Closes #144 
Problem occurs when PipelinedWrapper is set to `@in_pipeline = true`, multi call with a block gets saved to a future, which does not know how to save a block. Thus, everything happening within nested multi block gets lost. When pipelined block finishes and starts executing futures, there's only multi call without block which returns OK, and sets db to `@in_multi=true`.
Couple of words about my solution:
Same solution that is used for nested pipelined blocks within multi blocks does not work other way around, since `PipelinedWrapper` getting yielded to multi block in this case pushes them down the stack to multi wrapper that is not in multi mode, so any calls to multi-specific methods like `#discard` will return an error.
Working around that by explicitly setting multi wrapper …

Transaction nested within pipeline bug fix

---

lib/mock_redis/pipelined_wrapper.rb
spec/commands/pipelined_spec.rb
spec/transactions_spec.rb

Array replies were being flatted, when the result of #pipelined
should be an array of the values returns by each individual operation.

Fix pipelined array replies

---

lib/mock_redis/pipelined_wrapper.rb
spec/commands/pipelined_spec.rb

Results of operations way down nested pipelines were not being
returned back.
Keep a counter of pipelining nesting levels in order to infer
whether we are in pipelining mode or not.

Fix nested pipelining

---

lib/mock_redis/database.rb

Fixes #118 and #121 
`Array.bsearch` is in ruby 2.0.
The difference with #121 is that here we manually build the index search using plain bsearch _item_ on the array of (item, index) pairs, and then extract the index from it.
Before:
```
> bundle exec ruby performance.rb
setex
21.502102999947965
set
0.09983500000089407
```
After:
```
> bundle exec ruby performance.rb
setex
7.995712999952957
set
0.08754800003953278
```
Test file:
```ruby
require 'mock_redis'
require 'benchmark'
VALS = Array.new(10_000) do |i|
["some_key:#{i}", 3000 + rand(10)]
end
mr = MockRedis.new
puts 'setex', (
Benchmark.realtime do
VALS.each do |key, exp|
mr.setex(key, exp, 'some value')
end
end
)
puts 'set', (
Benchmark.realtime do
VALS.each do |key, exp|
mr.set(key, 'some value')
end
end
)
```

Improve performance of set_expiration

---

lib/mock_redis/transaction_wrapper.rb
spec/commands/watch_spec.rb

`watch` should be allowed to accept multiple keys as in `redis-rb` (https://github.com/redis/redis-rb/blob/448322f0faff320eacec82682314edefb1b12036/lib/redis.rb#L2372)

Fix watch to allow multiple keys

---

lib/mock_redis/string_methods.rb
spec/commands/get_spec.rb
spec/commands/xadd_spec.rb

Related to this issue: https://github.com/brigade/mock_redis/issues/157
Right now, the mock redis `SET` converts the key to a string but the `GET` method does not.
* This PR adds the conversion into the `GET` method and adds an another assertion to the current test that was supposed to catch this.
* This also adds a fix to the `xadd` tests where the keys were getting set without the prefix `mock-redis-test:`, so that multiple runs of the test suite were failing
Please let me know if you'd like any adjustments

Fix get set reversibility

---

lib/mock_redis/database.rb
spec/client_spec.rb

Implement close and disconnect

---

lib/mock_redis/string_methods.rb
spec/commands/set_spec.rb

`ActiveSupport::Cache::RedisStore` passes all options into methods. `Redis` ignores options that it doesn't need. But `MockRedis` expects ex/px as the last key in `options`. 
Example:
```
MockRedis.new.set(:test, '1', logger: Logger.new(STDOUT))
=> NoMethodError: undefined method `/' for #<Logger:0x00007fe1a7a74ca8>
```

Fix SET method for other options coming from Redis::Store

---

lib/mock_redis/set_methods.rb
spec/commands/srem_spec.rb

Related to this issue: https://github.com/sds/mock_redis/issues/165
`MockRedis#srem` currently dos not support passing an array of integers as argument, this PR fixes it.

Fix srem to allow passing an array of integers as argument

---

lib/mock_redis/hash_methods.rb
spec/commands/hdel_spec.rb

Close #167 
`hdel` now accepts hash keys in various way:
```ruby
redis.hdel('test-hash', 'key1', 'key2')
redis.hdel('test-hash', ['key1', 'key2'])
redis.hdel('test-hash', ['key1'], 'key2')
```

Fix inconsistent behavior between `Redis#hdel`, `MockRedis#hdel`

---

lib/mock_redis/utility_methods.rb
spec/commands/scan_spec.rb

This is for cases when block is provided with deletion:
```
redis = MockRedis.new
11.times { |x| redis.set("state:123#{x}", x) }
redis.scan_each(match: "state:123*") do |key|
redis.del(key)
end
```

Allow UtilityMethods#common_scan to receive exceeding cursor

---

lib/mock_redis/zset_methods.rb
spec/commands/zpopmax_spec.rb
spec/commands/zpopmin_spec.rb
spec/spec_helper.rb

redis-rb 4.1.0 introduced [zpopmin](https://redis.io/commands/zpopmin) and [zpopmax](https://redis.io/commands/zpopmax) commands.
Thoughts on adding them to this library as well? Took a first stab at it with some tests. Please let me know. Thanks!

Add zpopmin and zpopmax commands

---

lib/mock_redis/string_methods.rb
spec/commands/setex_spec.rb

Before: 
```ruby
[7] pry(main)> MockRedis.new.setex "key", 0, "value"
=> "OK"
[8] pry(main)> Redis.new.setex "key", 0, "value"
Redis::CommandError: ERR invalid expire time in setex
```

Raise Redis::CommandError error when setex called with a negative timeout

---

lib/mock_redis/zset_methods.rb

Ruby 2.7 will emit the following deprecation warning if we call =~ on an Integer:
`warning: deprecated Object#=~ is called on Integer; it always returns nil`

Do not call =~ on Integer

---

lib/mock_redis.rb
lib/mock_redis/database.rb
spec/commands/pipelined_spec.rb

Because `now` is defined on the `MockRedis` instance itself, it isn't captured in a "future" when capturing the pipelined block.
Before this change, the added test would return `['bar', 'baz']`, instead of `['bar', [1_546_398_246, 0], 'baz']`.
Moving `now` from `MockRedis` to `Database` was the simplest way to make this work given how the current futures implementation wraps around a database, which makes it cumbersome / non-idiomatic to capture data returned by the server itself.
I'm open to suggestions how we can make this more generic (i.e. any method on the server itself is captured, and we don't have to move this method to the database layer), without creating too much coupling between the different parts of the system (I don't think we want to start monkey patching the server within …

Support returning time in pipelines

---

lib/mock_redis/string_methods.rb
spec/commands/set_spec.rb

Because `expire` calls `to_i` on the provided value, any millisecond precision is lost when a floating-point value is passed in.
The `px` duration in `set` is already supplied as an integer representing milliseconds, so we can pass it straight to `pexpire`.
The test didn't catch this mistake because it was using exact seconds in its test.

fix: correctly set milliseconds ttl for set with px

---

lib/mock_redis/zset_methods.rb
spec/commands/zinterstore_spec.rb
spec/commands/zunionstore_spec.rb

Per [Redis Labs documentation](https://redislabs.com/ebook/part-1-getting-started/chapter-1-getting-to-know-redis/1-3-hello-redis/1-3-3-grouping-articles/), zinterstore and zunionstore should support passing unsorted sets to these commands with an implicit score of 1.0 applied to all values within the set.
> Redis has a command called ZINTERSTORE, which, when provided with SETs and ZSETs, will find those entries that are in all of the SETs and ZSETs, combining their scores in a few different ways (items in SETs are considered to have scores equal to 1).
Curiously, the ZINTERSTORE and ZUNIONSTORE command documentation [make no mention of this](https://github.com/antirez/redis-io/issues/172).  However, as referenced above this is officially supported, and patches [ensuring this …

support for unsorted sets within zinterstore/zunionstore

---

lib/mock_redis/future.rb
lib/mock_redis/transaction_wrapper.rb
spec/commands/future_spec.rb
spec/transactions_spec.rb

Fixing RuboCop errors in #184.

Handle block within multi block

---

lib/mock_redis/database.rb
lib/mock_redis/hash_methods.rb
lib/mock_redis/multi_db_wrapper.rb
lib/mock_redis/stream/id.rb
lib/mock_redis/string_methods.rb
mock_redis.gemspec
spec/commands/blpop_spec.rb
spec/commands/brpop_spec.rb
spec/commands/exists_spec.rb
spec/commands/hset_spec.rb
spec/commands/move_spec.rb
spec/commands/set_spec.rb
spec/commands/setbit_spec.rb
spec/commands/xadd_spec.rb
spec/commands/zrange_spec.rb
spec/commands/zrangebyscore_spec.rb
spec/commands/zrevrange_spec.rb
spec/commands/zrevrangebyscore_spec.rb
spec/spec_helper.rb
spec/support/redis_multiplexer.rb

Change exists return and add exists?

---

lib/mock_redis/stream.rb
lib/mock_redis/utility_methods.rb
spec/commands/del_spec.rb
spec/commands/xadd_spec.rb

XADD with maxlen 0 should create an empty stream

Fix XADD maxlen 0

---

lib/mock_redis/string_methods.rb
spec/commands/mget_spec.rb

- With redis
```
Redis.new.mget([])
```
- With mock_redis
```
MockRedis.new.mget([])
```

Raise error if passing empty array to mget

---

.travis.yml
lib/mock_redis/string_methods.rb
spec/commands/set_spec.rb

(Reopening in spite of Rubocop as I don't think this can be fixed another way)
One of the RSpec tests for the set command (spec/commands/set_spec.rb:36) checks the error that is raised when there is an unexpected argument. This is an error raised by Ruby and the format has changed slightly between versions 2.6 and 2.7. For example, for the test code:
```ruby
def test arg1: ; end
test(arg1: 0, arg2: 1)
```
the output is:
```
Traceback (most recent call last):
1: from test.rb:3:in `<main>'
test.rb:1:in `test': unknown keyword: arg2 (ArgumentError)
Traceback (most recent call last):
1: from test.rb:3:in `<main>'
test.rb:1:in `test': unknown keyword: :arg2 (ArgumentError)
```
This difference is enough to make the test fail.
To fix this while ensuring that the error is consistent with the …

Ruby 2.7 error in set rspec test

---

Gemfile
lib/mock_redis.rb
lib/mock_redis/expire_wrapper.rb
lib/mock_redis/geospatial_methods.rb
lib/mock_redis/multi_db_wrapper.rb
lib/mock_redis/pipelined_wrapper.rb
lib/mock_redis/transaction_wrapper.rb
spec/commands/del_spec.rb
spec/commands/xadd_spec.rb
spec/commands/xlen_spec.rb
spec/support/redis_multiplexer.rb

Ruby 3.0 handles keyword arguments differently: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
This attempts to fix that issue. Note there are still two warnings that I'm not sure how to fix in redis_multiplexer.rb method_missing.

Fix keyword arguments and stream specs

---

lib/mock_redis/string_methods.rb

for the offset argument. The redis client seems to allow for it.

Allow for passing a string value to the setbit method 

---

lib/mock_redis/connection_method.rb
lib/mock_redis/database.rb
spec/commands/connection_spec.rb
spec/spec_helper.rb

This adds the `#connection` method that the `redis` client gem has to `mock_redis`.
I also added a require for `ruby2_keywords` to the spec_helper.rb, without which the specs fail on ruby 2.6 (for me).

Add #connection method

---

lib/mock_redis/string_methods.rb

#200 setbit allow string value, but getbit not allow string value.
```
> require 'mock_redis'
> mr = MockRedis.new
> mr.set "key", "A"
> mr.setbit "key", "6", 1
NoMethodError: undefined method `/' for "6":String
from mock_redis-0.27.0/lib/mock_redis/string_methods.rb:96:in `getbit'
```
Fix above error.

Allow for passing a string value to the getbit method

---

lib/mock_redis/hash_methods.rb
spec/commands/hset_spec.rb

Since 4.0.0, hset has allowed a Hash to be sent instead of key value pairs.

hset was not accepting hashes as a parameter

---

lib/mock_redis/string_methods.rb
spec/commands/mget_spec.rb

From [redis-rb](https://github.com/redis/redis-rb/blob/6542934f01b9c390ee450bd372209a04bc3a239b/lib/redis.rb#L970), `mget` accepts a block.

Allow mget to accept a block

---

lib/mock_redis.rb
spec/mock_redis_spec.rb

This allows passing a `:logger` option to `MockRedis.new`. The logging method is mostly ripped from redis' implementation here: https://github.com/redis/redis-rb/blob/6542934f01b9c390ee450bd372209a04bc3a239b/lib/redis/client.rb#L329-L351. As a result it also logs call_time - I'm not sure that's especially useful for MockRedis, but have left it in for the sake of mimicking the Redis implementation.
See also #198

Add support for Redis' logger option

---

lib/mock_redis/zset.rb
spec/commands/zadd_spec.rb

Redis [represents zset scores as floats](https://redis.io/commands/ZADD) internally, but `mock_redis` attempts to [coerce zset scores to integers](https://github.com/sds/mock_redis/blob/master/lib/mock_redis/zset.rb#L27). This coercion prevents certain float values from being used as scores (eg. `Float::INFINITY`).
This PR removes the conditional type coercion from the zset `add` method, and instead converts all scores to floats.

Removing conditional type coercion for zset.add

---

README.md

I run the test against Redis 5.0.9 and there are 4 failed tests. When changing to Redis 6.2.1, all the tests pass. I think the documentation can be updated to avoid misunderstanding.

Update supported Redis to 6 in documentation

---

lib/mock_redis/database.rb

Raise `CommandError` on `redis.expire('a', nil)`

---

.github/workflows/lint.yml
.github/workflows/tests.yml
README.md

Quick update about version support.
While here, also fix the branch name since the default is now `main`.

Update README with Ruby/Redis version support

---

.github/workflows/tests.yml
Gemfile
spec/spec_helper.rb

Our migrations to GH Actions broke this since `TRAVIS` is not defined in this environment, and furthermore we needed to include some GH Actions to explicitly upload coverage reports.

Fix Coveralls to work on GH Actions

---

CHANGELOG.md
lib/mock_redis/version.rb

* Allow `ping` to take argument
* Raise `CommandError` on `hmget` with empty list of fields

Cut version 0.31.0

---

lib/mock_redis/string_methods.rb
spec/commands/psetex_spec.rb

Currently mock_redis does not work if used as [moneta](https://github.com/moneta-rb/moneta) backend because it [uses PSETEX](https://github.com/moneta-rb/moneta/blob/9c81f72a2a3922ab193523c8282e75b2cc44c560/lib/moneta/adapters/redis.rb#L52) to set the key expiration times in Redis. This PR adds basic support for [PSETEX](https://redis.io/commands/psetex/) command.

add support for PSETEX

---

README.md

Recommend to use the same docker image as the one [used in the CI](https://github.com/sds/mock_redis/blob/main/.github/workflows/tests.yml#L20-L24), as docker `redis` alias [represents version 7.x as of today](https://hub.docker.com/_/redis).

Update tests documentation in README.md

---

lib/mock_redis.rb
spec/client_spec.rb

Add [missing API from redis-rb](https://github.com/redis/redis-rb/blob/3037564001edb36a839b41b577c83241c85121a8/lib/redis.rb#L94-L96) (added in commit https://github.com/redis/redis-rb/commit/674541c5cc162b46066556811967a28a184f4665).
It is needed if you want to use `mock_redis` with `ActiveSupport::Cache::RedisCacheStore` from Rails 7.0 ([see source code](https://github.com/rails/rails/blob/04972d9b9ef60796dc8f0917817b5392d61fcf09/activesupport/lib/active_support/cache/redis_cache_store.rb#L239)).
Notes:
- Rails maintains [a similar patch](https://github.com/rails/rails/blob/v7.0.3.1/activesupport/lib/active_support/cache/redis_cache_store.rb#L22-L26) for `ConnectionPoolLike`.
- They switched from `with` to `then` on [Rails main …

Add MockRedis#with

---

lib/mock_redis/string_methods.rb
spec/commands/getdel.rb

This adds support to [GETDEL](https://redis.io/commands/getdel/) introduced in Redis 6.2.0 (implemented on commit https://github.com/redis/redis-rb/commit/94d606c04c0322600cf1c4dfe4ebba12155e7ea5)
I initially implemented it as
```ruby
def getdel(key)
get(key).tap { del(key) }
end
```
but I couldn't find `tap` usages on the codebase, so I preferred to introduce a variable, and return it after the `del` call. Please do let me know in case there's a standard to follow.
Thanks!

feat: Implement getdel command

---

README.md
lib/mock_redis/list_methods.rb
spec/commands/blmove_spec.rb
spec/commands/lmove_spec.rb

Added in Redis 6.2.0, the LMOV and BLMOVE commands succeed RPOPLPUSH and BRPOPLPUSH commands.

Add LMOVE and BLMOVE commands

---

lib/mock_redis/zset_methods.rb
spec/commands/zrem_spec.rb

When using zrem with an integer like this `zrem(@key, [11])` it did not convert the member to a string and therefore did not remove the member from the set.

Fix zrem with array of integers

---

.github/workflows/tests.yml
Gemfile
spec/commands/sscan_spec.rb
spec/support/redis_multiplexer.rb

Ruby 3.2 has [been released](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)! To build confidence in compatibility, let's add it to the build matrix, along with Ruby 3.1.

CI: add Ruby 3.1 and 3.2 to the test matrix

---

.rubocop.yml
lib/mock_redis.rb
lib/mock_redis/hash_methods.rb
lib/mock_redis/pipelined_wrapper.rb
lib/mock_redis/set_methods.rb
lib/mock_redis/stream.rb
lib/mock_redis/string_methods.rb
lib/mock_redis/transaction_wrapper.rb
lib/mock_redis/zset_methods.rb
mock_redis.gemspec
spec/commands/scan_spec.rb

In the [README.md](https://github.com/sds/mock_redis/blob/main/README.md#requirements) document the requirements sections notes Ruby 2.6+.
- Update the gemspec to enforce the Ruby >= 2.6 constraint.
- Target Ruby 2.6 with Rubocop and apply the suggestions it makes.
```
rubocop --autocorrect-all
```

Limit Ruby to 2.6 and above

---

.github/workflows/tests.yml
.rubocop.yml
README.md
lib/mock_redis.rb
mock_redis.gemspec

Ruby 2.6 reached its end of life in April 2022. It is no longer supported.
- Update the gemspec to enforce a Ruby >= 2.7 constraint.
- Remove the runtime dependency on the `ruby2_keywords` gem. The functionality provided by this gem comes out-of-the-box with Ruby since version 2.7.
- Remove Ruby 2.6 from the CI test matrix.
- Configure Rubocop to target Ruby 2.7.

Limit Ruby to 2.7 and above

---

mock_redis.gemspec

Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `homepage_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The links will be available on the [Rubygems project page](https://rubygems.org/gems/mock_redis), via the Rubygems API, and the `gem` and `bundle` command-line tools, after the next release.

Add project metadata to the gemspec

---

mock_redis.gemspec

There are a bunch of files in the gem package that aren't useful for downstream projects. Removing these reduces the gem package size from **72K** to **30K!**
<details><summary>contents diff</summary>
```diff
< .github/workflows/lint.yml
< .github/workflows/tests.yml
< .gitignore
< .mailmap
< .overcommit.yml
< .rspec
< .rubocop.yml
< .rubocop_todo.yml
< .simplecov
CHANGELOG.md
< Gemfile
LICENSE.md
README.md
< Rakefile
lib/mock_redis.rb
lib/mock_redis/assertions.rb
lib/mock_redis/connection_method.rb
lib/mock_redis/database.rb
lib/mock_redis/exceptions.rb
lib/mock_redis/expire_wrapper.rb
lib/mock_redis/future.rb
lib/mock_redis/geospatial_methods.rb
lib/mock_redis/hash_methods.rb
lib/mock_redis/indifferent_hash.rb
lib/mock_redis/info_method.rb
lib/mock_redis/list_methods.rb …
```

Reduce gem contents

---

lib/mock_redis/utility_methods.rb
lib/mock_redis/zset.rb
spec/commands/scan_each_spec.rb
spec/commands/scan_spec.rb

👋 This PR adds `type` option support to `scan` and `scan_each`. See the Redis docs [here](https://redis.io/commands/scan/#the-type-option).
In order to make testing easier, I also added an optional enumerator parameter to the intializer of `Zset`.
I also altered the `scan` and `scan_each` specs to define the `data` hash instead of `collection` key array, since the `Database#type` method requires inspecting the data hash's values.

Support #scan with type option

---

lib/mock_redis/database.rb
spec/commands/scan_each_spec.rb
spec/commands/scan_spec.rb

This PR adds support for scanning on keys containing hash tags. This is mainly relevant when working with Redis in cluster mode. If `mock_redis` is not supposed to support Cluster mode, I understand if you want to close this PR.
[Hash tags](https://redis.io/docs/management/scaling/) are parts of a key surrounded by `{}`. This is used in cluster mode to ensure a set of keys is stored on the same node. MockRedis does not support this and scanning on a key containing a hash tag does not work because the resulting regex pattern created by `redis_pattern_to_ruby_regex` does not escape curly braces.
The added commit is a suggestion on how support can be added. If there is a better way, feel free to edit directly or notify me and I will make the required change.

Add support for scanning on keys containing hash tags

---

CHANGELOG.md
lib/mock_redis/version.rb

* Require Ruby 2.7 or newer, since Ruby 2.6 and older are EOL
* Remove unnecessary files from gem contents
* Add support for popping multiple items with `lpop`
* Add support for `scan` with type option
* Add support for `sadd?`
* Add support for scanning on keys containing hash tags (`{...}`)

Cut version 0.37.0

---

CHANGELOG.md
lib/mock_redis/string_methods.rb
lib/mock_redis/version.rb
spec/commands/set_spec.rb

Related with this issue https://github.com/sds/mock_redis/issues/279 
* Documentation for the feature here: https://redis.io/commands/set/
* Added tests for SET ... EXAT and PXAT on a valid and invalid key
Hope you find it useful 😄

feat(set_exat_pxat): Add EXAT and PXAT arguments to the SET redis command

---

lib/mock_redis.rb
lib/mock_redis/database.rb
spec/commands/pipelined_spec.rb

Resolves https://github.com/sds/mock_redis/issues/278
Seems like everything is working; however, I'm not sure if moving `#call` from `MockRedis` to `MockRedis::Database` has some side-effects -- is there a reason `call` was separated from other commands?
I also changed `send` to `public_send` in `call` implementation (seems to be OK, I'm not sure if there are any edge cases when calling private is a usecase).
Also, I think we should allow mix-cased variants of Redis methods (`RedisMock.new.call(["GET", 123])` does not work right now, but redis commands are case insensitive).
Usage example:
```ruby
redis = MockRedis.new
redis.pipelined do |pipeline|
pipeline.call(["get", "foo"])
pipeline.call(["get", "bar"])
end
```

Implement `call` method in `pipelined` block

---

lib/mock_redis/set_methods.rb
spec/commands/sadd_spec.rb

We were flattening the wrapped array here to get rid of any nesting of arrays we might have accidentally done by wrapping with an Array literal (`[]`). Instead, `Kernel#Array` will leave an existing Array alone, and wrap any single object in an Array. This is consistent with real Redis' behavior.

Real Redis adds an Array as a stringified member

---

lib/mock_redis/database.rb
spec/commands/pipelined_spec.rb

Redis commands are case-insensitive.
`redis-rb` behavior:
```
[1] redis_connection.call(["sET", "foo", 1])
"OK"
[2] redis_connection.call(["GET", "foo"])
"1"
```

Make `call` method command name case-insensitive

---

.github/workflows/tests.yml
lib/mock_redis/database.rb
spec/commands/expire_spec.rb
spec/commands/expireat_spec.rb
spec/commands/pexpire_spec.rb
spec/commands/pexpireat_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/raises_on_invalid_expire_command_options.rb

Resolves https://github.com/sds/mock_redis/issues/286
I also addes some specs to run against redis 7. Some of the existing specs fail, so I marked new specs with `redis: 7.0` tag.
Running `bundle exec rspec --tag redis:7.0` should run only redis-7-related specs, and running with `redis:6.2` or without tag at all should run all the specs except of redis-7-related. Not sure if this is an appropriate/optimal solution

Add support for `expire`-related command options `nx`, `xx`, `lt` and `gt`

---

.github/workflows/lint.yml
.github/workflows/tests.yml
.rubocop.yml
Gemfile
README.md
lib/mock_redis/geospatial_methods.rb
mock_redis.gemspec

Ruby 2.7 reached EoL in March 2023. It's time to drop support since our CI is now complaining about Bundler not supporting Ruby < 3.

Require Ruby 3+

---

CHANGELOG.md
lib/mock_redis/version.rb

* Drop support for Ruby 2.x
* Add support for `srem?`

Cut version 0.42.0

---

lib/mock_redis/string_methods.rb
spec/commands/set_spec.rb

closes #292 
This pull request is for issue #292.
I extend set method to accept a third positional argument.
The primary goal of this change is to enhance the compatibility of the `mock_redis` `set` method with the `redis-store` `set` method. By introducing a third positional argument, we aim to align more closely with the `redis-store` implementation, facilitating easier integration and use in environments where `redis-store` is prevalent.
While the `redis-store` `set` method accepts three positional arguments, the standard Redis `set` method traditionally takes only two. This discrepancy could raise concerns about compatibility. However, this change ensures that compatibility with the standard Redis API is maintained and verified through existing tests in `set_spec.rb`. 
The `set` …

#292 extend set method to accept a third positional argument

---

lib/mock_redis/database.rb
lib/mock_redis/memory_method.rb
spec/commands/memory_spec.rb

`MEMORY USAGE key` currently results in `NoMethodError: undefined method 'memory' for #<MockRedis::Database...`
This change will return a hardcoded numeric value
```console
> m = MockRedis.new
> m.call(["memory", "usage", "foo"])
=> nil
> m.set("foo", "anything")
=> "OK"
> m.call(["memory", "usage", "foo"])
=> 160
```

Add support for `memory usage ...` command

---

.github/dependabot.yml

This PR adds a configuration to tell Dependabot to update the versions used for some well-known GitHub Actions, such as `checkout`, in order to avoid deprecation warnings when those get too old. [Documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)

CI: Let dependabot update GH Actions

---

lib/mock_redis/list_methods.rb
spec/commands/rpop_spec.rb
spec/support/shared_examples/does_not_cleanup_empty_strings.rb
spec/support/shared_examples/only_operates_on_lists.rb

`rpop` accepts an optional `count` argument to indicate how many elements should be removed and returned from the list
See https://github.com/redis/redis-rb/blob/9938411bd44383b795e05df900abce4df66daaef/lib/redis/commands/lists.rb#L114
Also had to change the shared examples a little bit to be able to pass the arguments they use and make a more accurate expectation on the error.
I think the `args_for_method` is making an assumption when the `arity < 0` and always using `[1, 2]` (+ the key), but that doesn't work in all cases. In particular, `rpop` now has `arity` `-2` (because it has 1 required arg + 1 optional) so calling `rpop(key, 1, 2)` was causing an argument error instead of `Redis::CommandError` (which we expect because of the redis value not being a list).
At first I tried to …

Add support for optional `count` arg in `rpop`

---

lib/mock_redis/hash_methods.rb
spec/commands/hset_spec.rb

Fixes https://github.com/sds/mock_redis/issues/310
This resolves an issue where `Redis` and `MockRedis` were storing values slightly differently:
```ruby
require 'redis'
redis = Redis.new
hash = {:name=>"job", :namespace=>"default", :klass=>"Job"}
redis.hset("key", hash.flatten)
redis.hgetall("key")
=> {"name"=>"job", "namespace"=>"default", "klass"=>"Job"}
```
```ruby
require 'mock_redis'
mock_redis = MockRedis.new
hash = {:name=>"job", :namespace=>"default", :klass=>"Job"}
mock_redis.hset("key", hash.flatten)
mock_redis.hgetall("key")
=> {"name"=>"job", "namespace"=>"default", "klass"=>"Job"}
```

Fix `hset` for Array of Key / Value Pairs

---

lib/mock_redis/database.rb
spec/commands/brpoplpush_spec.rb
spec/commands/lpop_spec.rb
spec/commands/pipelined_spec.rb
spec/spec_helper.rb

Fix for https://github.com/sds/mock_redis/issues/323
https://github.com/sds/mock_redis/pull/324 with specs fixed. Problem was that the arity of some methods changed from `redis 5.3.0` to `redis 5.4.0` due to https://github.com/redis/redis-rb/pull/1300

allow #call to accept array or multiple arguments

---

lib/mock_redis/hash_methods.rb
spec/commands/hmget_spec.rb

The previous version of `hmget` calls `hget` for each field being fetched, but that results in a lot of redundant calls to `with_hash_at` (and in turn, `clean_up_empties_at`, which is not especially fast).
Change it to just use a single `with_hash_at` call.
```ruby
days = 1.upto(365).map(&:to_s)
redis = MockRedis.new
Benchmark.ips do |x|
x.report("v1") { redis.hmget("views_by_year:2025", *days) }
x.report("v2") { redis.hmget2("views_by_year:2025", *days) }
x.compare!
end
```

Faster hmget when fetching a lot of fields
